// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_activities from "./routes/api/activities.ts";
import * as $api_analyze from "./routes/api/analyze.ts";
import * as $api_search from "./routes/api/search.ts";
import * as $index from "./routes/index.tsx";
import * as $DarkModeToggle from "./islands/DarkModeToggle.tsx";
import * as $UserSearch from "./islands/UserSearch.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/activities.ts": $api_activities,
    "./routes/api/analyze.ts": $api_analyze,
    "./routes/api/search.ts": $api_search,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/DarkModeToggle.tsx": $DarkModeToggle,
    "./islands/UserSearch.tsx": $UserSearch,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
